site_name: Rosta Group Wiki
nav:
- Home: index.md
- General Info: general_info/onboarding.md
- Members: members.md
- Knowledge Base: kb/topics.md


theme:
  name: mkdocs
  custom_dir: custom_theme/
  locale: en

plugins:
    - search
    - awesome-pages